### ISSUE TITLE
Should there be a Window Merger icon in the toolbar?

### ISSUE THREAD

**Issue by jwsmith601** [Zegnat/browserext-window-merger#15]
I see the Right-Click functionality but did not notice an icon created in the toolbar.  Should it be there?

Thanks for making this!

**Comment by Nomes77** [comment]
It occurs when you right-click on any tab.

**Comment by Zegnat** [comment]
Hi! Sorry, I missed this issue 😮 

No, the Window Merger add-on does not add any buttons. It only puts itself in context menus. Basically all places it shows up are visible in the screenshots.
