### ISSUE TITLE
Determine oldest Firefox version compatibility

### ISSUE THREAD

**Issue by grahamperrin** [Zegnat/browserext-window-merger#5]
When I first tested with recent Waterfox Classic 56.2.13, menu options were apparent. From a screen recording: 

![vlcsnap-2019-09-04-03h25m48s652](https://user-images.githubusercontent.com/192271/64221171-d3de0c00-cec3-11e9-9094-757145c7bd0d.png)

– however the windows did not merge.

The browser crashed (maybe because I was thrashing the OS, FreeBSD-CURRENT, at the time, with software builds). 

After relaunching the app: menu options are no longer apparent: 

![image](https://user-images.githubusercontent.com/192271/64221346-74ccc700-cec4-11e9-8513-488936c496db.png)

Can you add compatibility with Waterfox Classic? (Historically: Waterfox 56.0 was based on Firefox 56.0.2.)

Or does the extension need a `strict_min_version`?

**Comment by Zegnat** [comment]
I will go and figure out what the oldest version of Firefox is that can be supported by my code-base. This may end up including Firefox 56. If it is Waterfox that breaks the browser extension API, I can already say I will not be fixing that as I am not a Waterfox user.

I could be persuaded to accept PRs to lower the version requirements, or fix Waterfox. But I’ll leave that to separate issues when it comes up.

Definitely should add clear compatibility notes before the v1.0.0 release!

**Comment by Zegnat** [comment]
Upon first check: this extension does not support anything before Fx 62 because of [its use of flatMap](https://github.com/Zegnat/browserext-window-merger/blob/v0.2.0/background.js#L82) (see [browser compatibility](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap#Browser_compatibility)). This is why Waterfox 56.2.13 doesn’t seem to be able to run the action from the context menu.

**Comment by Zegnat** [comment]
Pushed a release limiting to Fx 62 for now, so I will not be giving people any false hopes while I look for a good minimum version to support.

My first feeling is to support down to the latest ESR release. This is currently 60.9.0. If Waterfox is API compatible with that release, all should be fine. I may not get to test with ESR ’til the upcoming weekend, which is one of the reasons for pushing a more limiting release first.

Thanks for you vigilance!

**Comment by Zegnat** [comment]
Closing this in favour of #6 and #7 to separately track older Firefox support and possible Waterfox support.

**Comment by Zegnat** [comment]
@grahamperrin just a friendly ping that, as of the [v0.4.0 release](https://github.com/Zegnat/browserext-window-merger/releases/tag/v0.4.0) Window Merger should be available on Waterfox 🎊

**Comment by grahamperrin** [comment]
@Zegnat belated thanks!
